# Generated by Django 5.1 on 2024-08-21 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_enry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enry',
            new_name='Entry',
        ),
    ]
