# Generated by Django 5.1 on 2024-08-21 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_rename_enry_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='txt',
            new_name='text',
        ),
    ]
